// <auto-generated />
using System;
using ForestProof.Backend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForestProof.Backend.Migrations
{
    [DbContext(typeof(ForestProofDbContext))]
    partial class ForestProofDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AoiId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InputHash")
                        .HasColumnType("char(64)");

                    b.Property<double>("KSensitivity")
                        .HasColumnType("numeric");

                    b.Property<string>("MethodVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Geometry>("RequestedGeometry")
                        .HasColumnType("geometry");

                    b.Property<string>("SclMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("YearEnd")
                        .HasColumnType("integer");

                    b.Property<int>("YearStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AoiId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Area", b =>
                {
                    b.Property<string>("AoiId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("AreaHectares")
                        .HasColumnType("numeric");

                    b.Property<MultiPolygon>("Geometry")
                        .HasColumnType("geometry (multipolygon)");

                    b.Property<string>("ParentAoiId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SelectionRole")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("AoiId");

                    b.HasIndex("ParentAoiId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Baseline", b =>
                {
                    b.Property<string>("AoiId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("HistoricalRateTcHaYr")
                        .HasColumnType("numeric");

                    b.Property<double>("ReferenceMean2015TcHa")
                        .HasColumnType("numeric");

                    b.Property<double>("ReferenceMean2019TcHa")
                        .HasColumnType("numeric");

                    b.HasKey("AoiId");

                    b.ToTable("Baselines");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.BaselineResultEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("EBase")
                        .HasColumnType("numeric");

                    b.Property<string>("QStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QUnits")
                        .HasColumnType("integer");

                    b.Property<double>("RAdj")
                        .HasColumnType("numeric");

                    b.Property<double>("RValue")
                        .HasColumnType("numeric");

                    b.Property<double>("ReserveB")
                        .HasColumnType("numeric");

                    b.Property<double>("Unc")
                        .HasColumnType("numeric");

                    b.HasKey("RunId");

                    b.ToTable("BaselineResults");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.CarbonMetrics", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<double>("CT0")
                        .HasColumnType("numeric");

                    b.Property<double>("CT1")
                        .HasColumnType("numeric");

                    b.Property<double>("CalculatedAreaHa")
                        .HasColumnType("numeric");

                    b.Property<double>("DeltaC")
                        .HasColumnType("numeric");

                    b.Property<double>("EPerHaYear")
                        .HasColumnType("numeric");

                    b.Property<double>("EProj")
                        .HasColumnType("numeric");

                    b.Property<double>("HValue")
                        .HasColumnType("numeric");

                    b.Property<double>("LBound")
                        .HasColumnType("numeric");

                    b.Property<double>("UBound")
                        .HasColumnType("numeric");

                    b.HasKey("RunId");

                    b.ToTable("CarbonMetrics");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ChangeZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaHa")
                        .HasColumnType("numeric");

                    b.Property<string>("CauseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ContributionTc")
                        .HasColumnType("numeric");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ChangeZones");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AoiId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("CloudFraction")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("ObservedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("uuid");

                    b.Property<double?>("ValidFraction")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AoiId");

                    b.HasIndex("SourceAssetId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Parameter", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parameter");

                    b.Property<string>("SourceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.HasKey("Name");

                    b.HasIndex("SourceId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AoiId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClaimedResult")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AoiId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uri")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RiskType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ScenarioValuation", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<double>("PriceRub")
                        .HasColumnType("numeric");

                    b.Property<double>("TotalValueRub")
                        .HasColumnType("numeric");

                    b.HasKey("RunId", "PriceRub");

                    b.ToTable("ScenarioValuations");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Source", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("SourceId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.SourceAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AoiId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Crs")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Sha256")
                        .HasColumnType("char(64)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AoiId");

                    b.HasIndex("SourceId");

                    b.ToTable("SourceAssets");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.YearlySeries", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<double>("CBarT")
                        .HasColumnType("numeric");

                    b.Property<double>("CT")
                        .HasColumnType("numeric");

                    b.HasKey("RunId", "Year");

                    b.ToTable("YearlySeries");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ZoneEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneEvidence");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.AnalysisRun", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Area", "Area")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("AoiId");

                    b.HasOne("ForestProof.Backend.Persistence.Entities.Project", "Project")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ForestProof.Backend.Persistence.Entities.User", "User")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("UserId");

                    b.Navigation("Area");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Area", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Area", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentAoiId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Baseline", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Area", "Area")
                        .WithOne("Baseline")
                        .HasForeignKey("ForestProof.Backend.Persistence.Entities.Baseline", "AoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.BaselineResultEntity", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.AnalysisRun", "Run")
                        .WithOne("BaselineResult")
                        .HasForeignKey("ForestProof.Backend.Persistence.Entities.BaselineResultEntity", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.CarbonMetrics", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.AnalysisRun", "Run")
                        .WithOne("CarbonMetrics")
                        .HasForeignKey("ForestProof.Backend.Persistence.Entities.CarbonMetrics", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ChangeZoneEntity", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.AnalysisRun", "Run")
                        .WithMany("ChangeZones")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Observation", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Area", "Area")
                        .WithMany("Observations")
                        .HasForeignKey("AoiId");

                    b.HasOne("ForestProof.Backend.Persistence.Entities.SourceAsset", "SourceAsset")
                        .WithMany("Observations")
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Parameter", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Source", "Source")
                        .WithMany("Parameters")
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Project", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Area", "Area")
                        .WithMany("Projects")
                        .HasForeignKey("AoiId");

                    b.HasOne("ForestProof.Backend.Persistence.Entities.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ReportEntity", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.AnalysisRun", "Run")
                        .WithMany("Reports")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Risk", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.AnalysisRun", "Run")
                        .WithMany("Risks")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ScenarioValuation", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.AnalysisRun", "Run")
                        .WithMany("ScenarioValuations")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.SourceAsset", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Area", "Area")
                        .WithMany("SourceAssets")
                        .HasForeignKey("AoiId");

                    b.HasOne("ForestProof.Backend.Persistence.Entities.Source", "Source")
                        .WithMany("SourceAssets")
                        .HasForeignKey("SourceId");

                    b.Navigation("Area");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.User", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.YearlySeries", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.AnalysisRun", "Run")
                        .WithMany("YearlySeries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ZoneEvidence", b =>
                {
                    b.HasOne("ForestProof.Backend.Persistence.Entities.SourceAsset", "SourceAsset")
                        .WithMany("ZoneEvidence")
                        .HasForeignKey("SourceAssetId");

                    b.HasOne("ForestProof.Backend.Persistence.Entities.ChangeZoneEntity", "Zone")
                        .WithMany("ZoneEvidence")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceAsset");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.AnalysisRun", b =>
                {
                    b.Navigation("BaselineResult");

                    b.Navigation("CarbonMetrics");

                    b.Navigation("ChangeZones");

                    b.Navigation("Reports");

                    b.Navigation("Risks");

                    b.Navigation("ScenarioValuations");

                    b.Navigation("YearlySeries");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Area", b =>
                {
                    b.Navigation("AnalysisRuns");

                    b.Navigation("Baseline");

                    b.Navigation("Children");

                    b.Navigation("Observations");

                    b.Navigation("Projects");

                    b.Navigation("SourceAssets");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.ChangeZoneEntity", b =>
                {
                    b.Navigation("ZoneEvidence");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Organization", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Project", b =>
                {
                    b.Navigation("AnalysisRuns");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.Source", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("SourceAssets");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.SourceAsset", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("ZoneEvidence");
                });

            modelBuilder.Entity("ForestProof.Backend.Persistence.Entities.User", b =>
                {
                    b.Navigation("AnalysisRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
